version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: dog_breed_nginx
    ports:
      - "80:80"
      - "443:443" # Dành cho HTTPS sau này
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
      # Volume để Nginx có thể phục vụ file đã upload trực tiếp
      - ./backend/uploads:/var/www/uploads
    depends_on:
      - frontend
      - backend
      - ai_service
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend # Build context là thư mục frontend
      dockerfile: Dockerfile
    container_name: dog_breed_frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000" # Expose Next.js dev server
    environment:
      - NODE_ENV=development

  backend:
    build: ./backend
    container_name: dog_breed_backend
    volumes:
      - ./backend:/server
      - /server/node_modules
    restart: unless-stopped
    depends_on:
      - ai_service
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000" 

  ai_service:
    build: ./ai_service
    container_name: dog_breed_ai_service
    # SỬA LỖI: Truyền biến môi trường từ file .env của backend vào container.
    # Điều này đảm bảo ai_service có thể kết nối tới MongoDB.
    env_file:
      - ./backend/.env
    restart: unless-stopped
