const options = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: "Dog Breed Prediction API",
      version: "1.0.0",
      description:
        "Tài liệu API cho hệ thống dự đoán giống chó, quản lý người dùng, và các module liên quan.",
    },
    servers: [
      {
        url: "http://localhost:3000",
        description: "Development Server",
      },
    ],
    tags: [
      { name: "Auth", description: "API xác thực và quản lý tài khoản" },
      { name: "Medias", description: "API quản lý media (ảnh, video)" },
      { name: "DogsWiki", description: "API quản lý thông tin các giống chó (wiki)" },
      { name: "Directories", description: "API quản lý thư mục logic" },
      { name: "Predictions", description: "API dự đoán, lưu lịch sử, stream, kiểm tra trạng thái" },
      { name: "AI Proxy", description: "API chuyển tiếp trực tiếp đến AI Service (không lưu DB)" },
      { name: "BFF-Prediction", description: "API tổng hợp cho chức năng dự đoán phía client" },
      { name: "BFF-Collection", description: "API tổng hợp cho chức năng bộ sưu tập (Pokedex) phía client" },
      { name: "BFF-Content", description: "API tổng hợp cho các chức năng hiển thị nội dung phía client" },
      { name: "BFF-Admin", description: "API tổng hợp cho các chức năng quản trị phía client" },
      { name: "BFF-User", description: "API tổng hợp cho chức năng quản lý tài khoản người dùng phía client" },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
        },
      },
      // Schemas will be generated by swagger-jsdoc from your route annotations
    },
    security: [
      {
        bearerAuth: [],
      },
    ],
    paths: {
      "/api/analytics/track-visit": {
        post: {
          security: [], // Bỏ qua yêu cầu xác thực cho endpoint này
          tags: ["Analytics"],
          summary: "Ghi nhận lượt truy cập trang (công khai)",
        },
      },
    },
  },
  apis: ["./src/routes/*.ts", "./src/routes/**/*.ts"],
};

module.exports = { options };